 on:
  push:
      branches:
        - main
name: 🚀 Deploy on demo server
jobs:
  web-deploy:
    name: 🎉 Deploy
    runs-on: ubuntu-latest
    steps:
    - name: 🚚 Get latest code
      uses: actions/checkout@v3

    - name: 📂 Sync files
      uses: SamKirkland/FTP-Deploy-Action@v4.3.4
      with:
        server: ${{ secrets.DEV_FTP_SERVER }}
        username: ${{ secrets.DEV_FTP_USERNAME }}
        password: ${{ secrets.DEV_FTP_PASSWORD }}
